### ISSUE TITLE
RealEx Connector does not have methods for accessing all results of the Security Code check

### ISSUE THREAD

**Issue by deanwilliams** [globalpayments/java-sdk#12]
When performing an OTB check and including the security code information, the JSON response includes three fields:

* CVN Result
* AVS Postcode Response
* AVS Address Response

These three fields are detailed in the developer documentation.

![Annotation 2020-06-29 144052](https://user-images.githubusercontent.com/474063/86012992-90d2c380-ba16-11ea-860a-92dc5fba1b60.png)

However, the Transaction object returned by the RealexConnector only has methods for accessing the CVN Result and the AVS Postcode Response. There is no method for getting the AVS Address Response.

Why is this field missing when it is listed in the documentation?

**Comment by pablodamiancoca** [comment]
Now the Transaction class has the getAvsAddressResponse() method. Check it you can use it in your code.

```
public class Transaction {
...
    public String getAvsAddressResponse() {
        return avsAddressResponse;
    }
...
}
```

**Comment by deanwilliams** [comment]
It might have that, but it isn;t being populated.

In the RealexConnector class under the mapResponse method, you can see only the AVS post code response is added to the Transaction
