### ISSUE TITLE
Passing Secure3dVersion.ANY during checkEnrollment in Secure3dService always defaults to 3DS v1

### ISSUE THREAD

**Issue by adnansorg** [globalpayments/java-sdk#25]
Passing the config values as below
```        
GatewayConfig config = new GatewayConfig();
...
config.setSecure3dVersion(Secure3dVersion.ANY);
```
The response XML will always default to `Secure3dVersion.ONE`

It's in your documentation that we need to check for `Secure3dVersion.TWO` enrolment first, then follow up with `Secure3dVersion.ONE` if the first request comes back with `enrolled = false`. Wouldn't it be nice to just send `Secure3dVersion.ANY` and prioritise the latest specification instead of sending two requests?

link to docs: https://developer.globalpay.com/api/3d-secure-two#3ds2-version

**Comment by securesubmit-buildmaster** [comment]
Hello,

Thanks for the feedback. I am not sure I follow the issue you're trying to raise. 3DS1 and 3DS2 are handled by two entirely different services, so the default to each of the services will be the version of 3DS which applies only to that service. When trying against ANY both services need to be called in the event of an enrolled - false on 3DS2.
