### ISSUE TITLE
RealexConnector does not support reporting

### ISSUE THREAD

**Issue by j-davies** [globalpayments/java-sdk#8]
The current version of the Realex Connector does not support any reporting options, even though there is some commented out code for loading a transaction details:

https://github.com/globalpayments/java-sdk/blob/master/src/main/java/com/global/api/gateways/RealexConnector.java#L899

Are there plans on adding support for this, especially for the `ReportType.OpenAuths` report type?

**Comment by russelleverett** [comment]
Thanks for your comments.

While the GP Ecommerce gateway does support reporting, access to the reporting API calls are restricted. I would contact them directly to see how they recommend pulling this information.
